### ISSUE TITLE
Latest python RPMs

### ISSUE THREAD

**Issue by siva-kranthi** [intel/fMBT#18]
Pls let me know where we can find latest python RPMs. We have some old RPMs, but after installing them we are not able to open any settings like wi-fi settings to connect to wi-fi.

Pls let me know is it possible to create RPMs ourself?

**Comment by SivaKranthiKumar** [comment]
Tizen 2.3 Python RPMs - http://download.tizen.org/releases/2.3/2.3-mobile/tizen-2.3-mobile_20150206.1/repos/target/packages/armv7l/

**Comment by SivaKranthiKumar** [comment]
Latest RPMs - http://download.tizen.org/releases/2.3/2.3-mobile/tizen-2.3-mobile_20150311.3/repos/target/packages/armv7l/
