### ISSUE TITLE
[fmbttizen]:File to modify to get the hardware keys working

### ISSUE THREAD

**Issue by madhav-pai** [intel/fMBT#31]
Hi Antti,

Hope you are doing good,
We have a new spec (Tizen) for which we want to get working home key, back key, menu key, power , volume etc request you to please let me know the place and procedure to get it working.

Pls let me know the file to modify and what are the values it should be populated with.

Thanks
Madhav pai

**Comment by amazpyel** [comment]
Hello @askervin !

I have troubles with this issue. I'm trying to modify **fmbttizen-agent.py** but not successfully.  

_Details_
pressMenu() and pressBack() work as pressHome(). 

`python /tmp/fmbtuinput.py -p /dev/input/event*` output:

_Menu button:_
`event3     6117.551188 type:    1 (EV_KEY), code:   169 (      KEY_PHONE) value:        1`
_Back button:_
`event3     6185.121413 type:    1 (EV_KEY), code:   158 (       KEY_BACK) value:        1`

`sdb shell cat /proc/bus/input/devices | egrep "Name|Handlers"` output:

```shell
N: Name="max77693-muic"
H: Handlers=event0 sec-input-bridge kbd 
N: Name="gpio-keys"
H: Handlers=event1 sec-input-bridge kbd 
N: Name="sec_touchscreen"
H: Handlers=mouse0 event2 
N: Name="melfas-touchkey"
H: Handlers=event3 kbd 
```

So, what should I do? Both buttons (Back and Menu) are event 3 and name is "melfas-touchkey", am I right? 

And device name is "max77693-muic" as I understand and it's alreay present in `if .. else`.

**Comment by askervin** [comment]
I'd suggest adding new ``elif ... elif`` branch to hardware detection for this particular hw model. It will make sure that fmbttizen.py will work with existing models that contain "max77693-muic" but not "melfas-touchkey". That is:

```
...
elif 'max77693-muic' in devices and 'melfas-touchkey' in devices:
    debug("detected max77693-muic with melfas-touchkey")
    hwKeyDevice = {
        "POWER": "gpio-keys",
        "VOLUMEUP": "gpio-keys",
        "VOLUMEDOWN": "gpio-keys",
        "HOME": "gpio-keys",
        "MENU": "melfas-touchkey",
        "BACK": "melfas-touchkey",
        }
    _inputKeyNameToCode["HOME"] = 139
    _inputKeyNameToCode["MENU"] = 169
    if iAmRoot:
        touch_device = openTouchDevice(_opt_touch, "name:sec_touchscreen")
elif 'max77693-muic' in devices:
    [untouched old branch, keeps support for devices without melfas-touchkey...]
```

If you know more reliable way of detecting the hardware model than reading device names, feel free to use it. I'm not very happy with the current device-based detection method.

**Comment by amazpyel** [comment]
Thank, you. I got an idea.
