### ISSUE TITLE
FMBT windows installer error - libpcre-1.dll is missing 

### ISSUE THREAD

**Issue by ravikohli2002** [intel/fMBT#61]
After installing fmbt on windows after creating windows installer, I am getting error libpcre-1.dll is missing.
I have used fedora25 to create the windows installer. Can someone please let me know if this a known issue.

**Comment by askervin** [comment]
I have heard about this issue once earlier. It has probably appeared with new MinGW on Fedora 25.

As a workaround, I'd recommend using Fedora 23 for building the installer. (Fedora 23 Docker works fine for me.)

I'll leave this bug open to track when fMBT installer building works on Fedora 25. And I'd be very interested to hear if someone has ideas how to fix it.

**Comment by ravikohli2002** [comment]
Hi Antti,

I manually copied the missing dll in the install directory but now I am getting error "gspawn-win64-helper-console.exe has stopped working".

Is it possible for you to share working copy of windows installer. 

Thanks & Kind Regards,

**Comment by askervin** [comment]
Sorry about the delay. In case you are still interested in trying out Windows installer, please contact me at antti.kervinen@intel.com.

**Comment by ravikohli2002** [comment]
Hello Antti,

I was able to create windows installer using Fedora 23 and it works fine.
Thanks for your time and help.

Thanks & Kind Regards,

Ravi Kohli

**Comment by askervin** [comment]
Community builds on fMBT Windows installers are available here:

https://gitlab.com/fmbt/fmbt_ci/-/jobs

Click [Passed] build_windows_64, then [Browse] Job artifacts on the right.
